export const state = {
  page:'dashboard',
  properties:[],
  tenants:[],
  payments:[],
  expenses:[],
  maintenance:[],
  contractors:[],
  filters:{props:'all',tenants:'all',rent:'all',expenses:'overview',maint:'open',maintView:'requests',
    rentPeriod:'week', rentTab:'today', expMonth:'all', expCompany:'', landlords:'all', schedTab:'all', dashCompany:'', propCompany:'', landlordCompany:'',
    propQ:'', tenantQ:'', tenantProp:'', roomQ:'', roomArea:'all', roomType:'all', roomSort:'price_asc',
    expQ:'', expMin:'', expMax:'', expSort:'date_desc',
    maintQ:'', maintProp:'', maintContractor:'',
    rentSource:'all'
  },
  rentSchedule:[],
  /** Resolved in renderDashboard to current month (see ensureDashboardMonth). */
  dashMonth:'',
  propDetailTab:null,
  tenantDetailTab:null,
  roomMedia:{},
  vault:{},
  voidDates:{},
  propDocs:{},
  lateFeeConfig:{graceDays:3, feeType:'fixed', feeAmount:25, enabled:true},
  currentUser:{id:'', name:'Loading...', initials:'U', role:'viewer', email:''},
  users:[],
  roles:{
    admin:    {label:'Admin',   color:'#8B5CF6',bg:'#F5F3FF',icon:'👑',
               pages:['dashboard','properties','tenants','communication','rent','expenses','maintenance','landlords','rooms','diary','reports','settings','users'],
               canEdit:true,canDelete:true,canAddTenant:true,canMarkPaid:true,canViewFinancials:true,canManageUsers:true},
    manager:  {label:'Manager',color:'#3B82F6',bg:'#EFF6FF',icon:'💼',
               pages:['dashboard','properties','tenants','communication','rent','expenses','maintenance','rooms','diary','reports'],
               canEdit:true,canDelete:false,canAddTenant:true,canMarkPaid:true,canViewFinancials:true,canManageUsers:false},
    maintenance:{label:'Maintenance',color:'#F59E0B',bg:'#FFFBEB',icon:'🔧',
               pages:['dashboard','maintenance','properties','rooms','diary'],
               canEdit:false,canDelete:false,canAddTenant:false,canMarkPaid:false,canViewFinancials:false,canManageUsers:false},
    viewer:   {label:'Viewer', color:'#64748B',bg:'#F8FAFC',icon:'👁️',
               pages:['dashboard','properties','tenants','rent','rooms','diary','reports'],
               canEdit:false,canDelete:false,canAddTenant:false,canMarkPaid:false,canViewFinancials:false,canManageUsers:false},
  },
  landlords:[],
  landlordPayments:[],
  companies:[],
  config:{},
  maintExtras:{},
  dealInputs:{},
};
