create table public.properties (
  id uuid not null default extensions.uuid_generate_v4 (),
  name text not null,
  address text null,
  postcode text null,
  area text null,
  type text null default 'HMO'::text,
  rooms integer null default 0,
  occupied integer null default 0,
  rent numeric(10, 2) null default 0,
  landlord_rent numeric(10, 2) null default 0,
  landlord_id uuid null,
  landlord_name text null,
  maps_url text null,
  notes text null,
  created_at timestamp with time zone null default now(),
  room_list jsonb null default '[]'::jsonb,
  company_id text null,
  ownership_type text null default 'managed'::text,
  letting_type text null default 'hmo'::text,
  bedrooms integer null,
  mortgage jsonb null,
  purchase_info jsonb null,
  org_id uuid null,
  constraint properties_pkey primary key (id),
  constraint properties_landlord_id_fkey foreign KEY (landlord_id) references landlords (id),
  constraint properties_org_id_fkey foreign KEY (org_id) references organisations (id)
) TABLESPACE pg_default;